# Generated by Django 3.2.9 on 2022-01-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('batch', models.IntegerField()),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
